### ISSUE TITLE
Continuous Delivery

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/PyDV#225]
- [x] Release notes on single page #231 
- [x] Test suite #226 
- [x] Automated testing leading to tag and pre-release. #230 
- [x] Scripts for testing on RZ and releasing on LC machines. #238
